# Generated by Django 5.2 on 2025-05-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='last_order',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='regular_holiday',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
